export const ON_GET_INFO_LIST_REQUESTED = 'ON_GET_INFO_LIST_REQUESTED'
export const ON_GET_INFO_LIST_SUCCEEDED = 'ON_GET_INFO_LIST_SUCCEEDED'
export const ON_GET_INFO_LIST_FAILED = 'ON_GET_INFO_LIST_FAILED'

export default {
    ON_GET_INFO_LIST_REQUESTED,
    ON_GET_INFO_LIST_SUCCEEDED,
    ON_GET_INFO_LIST_FAILED
}