export const ON_LOGIN_IN_REQUESTED = 'ON_LOGIN_IN_REQUESTED'
export const ON_LOGIN_IN_SUCCEEDED = 'ON_LOGIN_IN_SUCCEEDED'
export const ON_LOGIN_IN_FAILED = 'ON_LOGIN_IN_FAILED'

export default {
    ON_LOGIN_IN_REQUESTED,
    ON_LOGIN_IN_SUCCEEDED,
    ON_LOGIN_IN_FAILED
}